### ISSUE TITLE
clarification: peptide-MHC affinity matrix shape, NaN percentage

### ISSUE THREAD

**Issue by evanbiederstedt** [hammerlab/mhcflurry-icml-compbio-2016#1]
Hi @timodonnell and @iskandr,

Clarification question: 

```
A dataset of peptide-MHC affinities for n peptides and a alleles may be thought of as a n × a matrix
where peptide/allele pairs without measurements are missing values.
```

Using the dataset BD2009, it appears that you also filtered out peptides which occurred in at least three alleles and alleles with less than five measurements. 

Did you measure percentage of `NaN` values you are imputing (i.e. how sparse is this matrix)? When doing the evaluation of imputation methods, what was the size of this (n,a) matrix? 

Also, apologies for the simple question, but I'm slightly confused by the pre-print. Based on [Kim et al, 2014](http://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-15-241), BD2009 contains 79 alleles, and 170 total datasets. Your BD2009 dataset has 106 alleles? And it was compiled into a single dataset?

**Comment by timodonnell** [comment]
That's a good point @evanbiederstedt that the number of alleles in our dataset (106) doesn't seem to match Table 1 in the Kim et al paper! I'm not sure what's causing the discrepancy, will have to dig into it.

I'm not sure about the exact sizes used for the evaluation of imputation methods since Alex ran that, but for the imputation used on the held-out data, we required 5 observations per peptide and 2 observations per allele. The matrix was 11707 peptides x 88 alleles and had NANs at 89.6% of the entries.

**Comment by evanbiederstedt** [comment]
Thanks @timodonnell 

> The matrix was 11707 peptides x 88 alleles and had NANs at 89.6% of the entries.

That checks out. I'll check the percentage of NaN's in the benchmarking of imputation methods. I believe it's in the notebooks.

**Comment by iskandr** [comment]
@evanbiederstedt They seem to be showing allele counts after some sort of filtering. One thing I noticed in their table is that they don't include alleles with fewer than 50 samples, which gets you down from 106 to 86. 

```
In [8]: len(df["mhc"].value_counts() >= 50)
Out[8]: 106

In [9]: sum(df["mhc"].value_counts() >= 50)
Out[9]: 85
```

I suspect if you add in some filtering criteria relating to having at least one strong binder and one non-binder we'd get down to 79. 

I'm not sure what they mean by "dataset" though -- maybe the distinct CSVs for each allele + peptide length?

**Comment by iskandr** [comment]
Oh, it's clarified right there in the paper: 

> In the table, only those data sets for which (MHC, length) combinations were shared between BD2009 and Blind and that had at least 50 data points are reported.

**Comment by evanbiederstedt** [comment]
@iskandr This makes sense. Thanks!

Feel free to close.
